name: Build JAR (Vaadin Prod)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build Maven (produção)
        run: |
          if [ -f ./mvnw ]; then
            ./mvnw -B -Pproduction -Dmaven.test.skip=true clean package
          else
            mvn -B -Pproduction -Dmaven.test.skip=true clean package
          fi

      - name: Copiar JAR para a raiz do workspace
        shell: bash
        run: |
          shopt -s globstar nullglob
          cp **/target/*.jar .

      - name: Publicar artefacto (.jar)
        uses: actions/upload-artifact@v4
        with:
          name: app-jar-${{ github.ref_name }}-${{ github.run_number }}
          path: |
            **/target/*.jar
            ./*.jar
          if-no-files-found: error
          retention-days: 7

      - name: Listar ficheiros na raiz do workspace
        run: ls -lah

